"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Icon } from "@/components/dashboard/icons";
import { CompanyLogo } from "@/components/shipments/shipments-page";
import { invoices, type Invoice } from "@/data/invoices";
import styles from "./invoices.module.css";

const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2});

function MobileBar({open}:{open:()=>void}){return <header className={styles.mobileBar}><i/><strong>Invoices & Billing</strong><button type="button" onClick={open}>☰</button></header>}
function Drawer({close}:{close:()=>void}){return <div className={styles.drawerBack} onClick={close}><aside onClick={event=>event.stopPropagation()}><button onClick={close}>×</button><nav><Link href="/dashboard"><Icon name="grid"/>Dashboard</Link><Link href="/shipments"><Icon name="truck"/>Shipments</Link><Link className={styles.active} href="/invoices"><Icon name="invoice"/>Invoices & Billing</Link></nav></aside></div>}
function Footer(){return <footer className={styles.footer}><div><b>Copyright © 2025 Peterdraw</b><span>Privacy Policy</span><span>Term and conditions</span><span>Contact</span></div><div><span>ⓕ</span><span>𝕏</span><span>◎</span><span>▷</span><span>in</span></div></footer>}

function PaidInvoiceIcon(){return <svg aria-hidden="true" width="28" height="28" viewBox="0 0 28 28" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2.75 17.1 5l3.82-.12.92 3.7 3.16 2.14-1.4 3.55 1.4 3.55-3.16 2.14-.92 3.7-3.82-.12L14 25.8l-3.1-2.26-3.82.12-.92-3.7L3 17.82l1.4-3.55L3 10.72l3.16-2.14.92-3.7L10.9 5 14 2.75Z"/><path d="m9.75 14.2 2.75 2.75 5.75-5.75"/></svg>}
function UnpaidInvoiceIcon(){return <svg aria-hidden="true" width="28" height="28" viewBox="0 0 28 28" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M5.25 3.75h17.5v20.5l-2.9-1.75-2.92 1.75L14 22.5l-2.93 1.75-2.92-1.75-2.9 1.75V3.75Z"/><path d="m11.25 10.75 5.5 5.5m0-5.5-5.5 5.5"/></svg>}
function Summary(){const cards=[["Paid Invoices","$28,890","350",<PaidInvoiceIcon key="paid-icon"/>],["Unpaid Invoices","$16,700","120",<UnpaidInvoiceIcon key="unpaid-icon"/>],["Pending Invoices","$8,050","80","◌"],["Overdue Invoices","$22,110","245","◷"]];return <div className={styles.summary}>{cards.map(card=><article key={card[0] as string}><span>{card[3]}</span><div><small>{card[0]}</small><strong>{card[1]}</strong><p>from <b>{card[2]}</b> Invoices</p></div></article>)}</div>}
function Status({value}:{value:Invoice["status"]}){return <span className={`${styles.status} ${styles[value.toLowerCase()]}`}>{value}</span>}
function Company({invoice}:{invoice:Invoice}){return <div className={styles.company}><i><CompanyLogo company={invoice.company}/></i><span><b>{invoice.company}</b><small>{invoice.shippingId}</small></span></div>}
function InvoiceSortIcon(){return <svg aria-hidden="true" className={styles.sortIcon} viewBox="0 0 8 10" fill="none" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round" strokeLinejoin="round"><path d="m2 3 2-2 2 2M6 7 4 9 2 7"/></svg>}
function InvoiceHeader({label,className}:{label:string;className?:string}){return <th className={className}><button type="button" className={styles.sortHeader}>{label}<InvoiceSortIcon/></button></th>}

function InvoiceList({selected,setSelected,query,setQuery,muted=false}:{selected:Invoice;setSelected:(invoice:Invoice)=>void;query:string;setQuery:(value:string)=>void;muted?:boolean}){
 const filtered=invoices.filter(item=>`${item.id} ${item.company} ${item.shippingId}`.toLowerCase().includes(query.toLowerCase()));
 return <section className={`${styles.list} ${muted?styles.muted:""}`}><header><h2>Invoices</h2><div><label><Icon name="search"/><input placeholder="Search invoices" value={query} onChange={event=>setQuery(event.target.value)}/></label><button title="Filter">☷</button><button>New Invoice</button></div></header><div className={styles.tableWrap}><table><thead><tr><th className={styles.selectionHeader}><span className={styles.indeterminateControl} aria-hidden="true"/></th><InvoiceHeader label="Invoice ID" className={styles.invoiceColumn}/><InvoiceHeader label="Company" className={styles.companyColumn}/><InvoiceHeader label="Shipping ID"/><InvoiceHeader label="Date"/><InvoiceHeader label="Amount"/><InvoiceHeader label="Status"/></tr></thead><tbody>{filtered.map(invoice=><tr key={invoice.id} className={selected.id===invoice.id?styles.selected:""} onClick={()=>setSelected(invoice)}><td><input type="checkbox" aria-label={`Select ${invoice.id}`} checked={selected.id===invoice.id} onChange={()=>setSelected(invoice)}/></td><td className={styles.invoiceColumn}><b>{invoice.id}</b><span>▧</span></td><td className={styles.companyColumn}><Company invoice={invoice}/></td><td>{invoice.shippingId}</td><td><span>{invoice.issueDate} <small>(Issued)</small></span><span>{invoice.dueDate} <small>(Due)</small></span></td><td>{money(invoice.amount)}</td><td><Status value={invoice.status}/></td></tr>)}</tbody></table></div></section>
}

function Details({invoice}:{invoice:Invoice}){const subtotal=invoice.items.reduce((sum,item)=>sum+item.price*item.quantity,0);const tax=subtotal*.08;const fee=10;const total=subtotal+tax+fee;return <section className={styles.details}><header><h2>‹ <span>Invoice Details</span></h2><div><button>Edit</button><button>Hold</button><button>Send Invoice</button></div></header><div className={styles.detailCard}><div className={styles.invoiceTitle}><div><b>Invoice <span>#{invoice.id}</span></b><Status value={invoice.status}/></div><p><span>Issue Date <b>{invoice.issueDate}</b></span><span>Due Date <b>{invoice.dueDate}</b></span></p></div><div className={styles.addresses}><div><small>Bill From</small><strong>{invoice.company}</strong><span>{invoice.email}</span><span>{invoice.address}</span><span>{invoice.phone}</span></div><div><small>Bill To</small><strong>ShipNow Logistics</strong><span>accounts@shipnow.com</span><span>901 Distribution Ave, Charlotte, NC 28217, USA</span><span>+1 704-555-9911</span></div></div><h3>Package Summary</h3><div className={styles.items}><table><thead><tr><th>Description ↕</th><th>Shipment Type ↕</th><th>Price ↕</th><th>Qty ↕</th><th>Amount ↕</th></tr></thead><tbody>{invoice.items.map((item,index)=><tr key={`${item.description}-${index}`}><td>{item.description}</td><td>{item.shipmentType}<small>{item.service}</small></td><td>{money(item.price)}</td><td>{item.quantity}</td><td>{money(item.price*item.quantity)}</td></tr>)}</tbody></table><dl><div><dt>Sub Total</dt><dd>{money(subtotal)}</dd></div><div><dt>Tax (8%)</dt><dd>{money(tax)}</dd></div><div><dt>Fee</dt><dd>{money(fee)}</dd></div><div><dt>Total</dt><dd>{money(total)}</dd></div></dl></div><div className={styles.note}><small>Note</small><p>Please process payment by the due date to avoid delivery disruption. Late fees may apply after 3 business days past due.</p></div></div><div className={styles.mobileActions}><button>Edit</button><button>Hold</button><button>Send Invoice</button></div></section>}

export function InvoicesPage(){const[selected,setSelected]=useState(invoices[7]);const[query,setQuery]=useState("");const[drawer,setDrawer]=useState(false);const selectedInvoice=useMemo(()=>invoices.find(item=>item.id===selected.id)??invoices[7],[selected]);return <><MobileBar open={()=>setDrawer(true)}/>{drawer&&<Drawer close={()=>setDrawer(false)}/>}<main className={styles.page}><header className={styles.pageHead}><div><h1>Invoices & Billing</h1><p><b>Dashboard</b><span>/</span>Invoices & Billing</p></div><label><Icon name="search"/><input placeholder="Search anything"/></label></header><Summary/><div className={styles.desktopLayout}><InvoiceList selected={selectedInvoice} setSelected={setSelected} query={query} setQuery={setQuery}/><Details invoice={selectedInvoice}/></div><div className={styles.tabletLayout}><InvoiceList selected={selectedInvoice} setSelected={setSelected} query={query} setQuery={setQuery}/><div className={styles.tabletDetail}><InvoiceList muted selected={selectedInvoice} setSelected={setSelected} query={query} setQuery={setQuery}/><Details invoice={selectedInvoice}/></div></div><Footer/></main></>}
