"use client";

import { useState } from "react";
import { Icon } from "@/components/dashboard/icons";
import { AuthenticatedSidebarContent } from "@/components/dashboard/authenticated-sidebar-content";
import { activities, packageStatuses, storageRows, warehouseFloors, warehouseSummary } from "@/data/warehouse";
import { WarehouseInventory } from "./warehouse-inventory";
import styles from "./warehouse.module.css";
import "./warehouse-fixes.module.css";

const More=()=> <Icon name="more" className={styles.more}/>;

function MobileBar({open}:{open:()=>void}){return <header className={styles.mobileBar}><i/><strong>Warehouse</strong><button type="button" onClick={open} aria-label="Open navigation">☰</button></header>}
function Drawer({close}:{close:()=>void}){return <div className={styles.drawerBack} onClick={close}><aside onClick={event=>event.stopPropagation()}><AuthenticatedSidebarContent active="Warehouse" onNavigate={close} onClose={close}/></aside></div>}
function Footer(){return <footer className={styles.footer}><div><b>Copyright © 2025 Peterdraw</b><span>Privacy Policy</span><span>Term and conditions</span><span>Contact</span></div><div><span>ⓕ</span><span>𝕏</span><span>◎</span><span>▷</span><span>in</span></div></footer>}

function FreightTabs(){return <div className={styles.freight}><button className={styles.freightActive}><Icon name="truck"/>Road Freight</button><button><span>▥</span><b>Rail Freight</b></button><button><span>◴</span><b>Ocean Freight</b></button><button><span>✈</span><b>Air Freight</b></button></div>}
function Summary(){return <div className={styles.summary} style={{width:"100%",minWidth:0}}>{warehouseSummary.map(item=><article key={item.label} style={{minWidth:0,overflow:"hidden"}}><small>{item.label}</small><div><strong>{item.value}</strong>{item.suffix&&<span>{item.suffix}</span>}<em>⌁ {item.change}</em></div></article>)}</div>}
function Capacity(){return <section className={styles.capacity}><header><h2>Capacity Usage</h2><More/></header><div className={styles.ring} style={{"--usage":`${62.5*3.6}deg`} as React.CSSProperties}><div><span>Total Usage</span><strong>62.5%</strong></div></div><div className={styles.capacityLegend}><p><span>Loaded</span><b>40 shelves</b></p><p><span>Empty</span><b>24 shelves</b></p></div></section>}
function Packages(){return <section className={styles.packages}><header><h2>Package Status</h2><More/></header><div className={styles.statusTabs}><button>All</button><button>Expected</button><button>Received</button><button>Sent</button></div><div className={styles.packageList}>{packageStatuses.map(item=><article key={item.id}><i><Icon name="box"/></i><p><b>{item.id}</b><span>{item.date}</span></p><em className={styles[item.status.toLowerCase()]}>{item.status}</em></article>)}</div></section>}
function Storage(){return <section className={styles.storage}><header><h2>Warehouse Storage</h2><div><button>▽ Filter⌄</button><span>Sort by:</span><button>Section⌄</button><More/></div></header><div className={styles.storageScroll}><table><thead><tr><th>Floor ↕</th><th>Section ↕</th><th>Category ↕</th><th>Storage Used ↕</th><th>Percentage ↕</th><th>Available Space ↕</th></tr></thead><tbody>{storageRows.map(row=><tr key={row.section}><td>{row.floor}</td><td>{row.section}</td><td>{row.category}</td><td><div><i style={{width:`${row.used}%`}}/></div></td><td><b>{row.used}%</b></td><td><b>{row.available}</b><span>/100</span></td></tr>)}</tbody></table></div></section>}
function WarehouseMap({floor,setFloor}:{floor:number;setFloor:(floor:number)=>void}){const zones=warehouseFloors[floor];return <section className={styles.map} style={{overflow:"hidden"}}><header><h2>Warehouse Map</h2><div>{[1,2,3].map(value=><button key={value} className={floor===value?styles.floorActive:""} onClick={()=>setFloor(value)}>Floor {value}</button>)}</div></header><div className={styles.mapCanvas}><div className={`${styles.zones} warehouse-mobile-zone-grid`}>{zones.map(zone=><article key={zone.name} style={{minWidth:0,overflow:"hidden"}}><h3>{zone.name}</h3><div>{Array.from({length:zone.slots},(_,index)=>index+1).map(slot=><span className={zone.full.includes(slot)?styles.full:""} key={slot}>{zone.prefix}{slot}</span>)}</div><p>Available Space <b>{zone.available}/100</b></p></article>)}</div><p className={styles.mapLegend}><span/>Available <span/>Full</p></div></section>}
function Activity(){return <section className={styles.activity}><header><h2>Warehouse Activity Log</h2><More/></header><div>{activities.map(item=><article key={item.name}><i className={item.purple?styles.purple:""}>{item.icon}</i><p><span><b>{item.name}</b> {item.text}</span><small>{item.time}</small></p></article>)}</div></section>}

export function WarehousePage(){const[floor,setFloor]=useState(1);const[drawer,setDrawer]=useState(false);return <><MobileBar open={()=>setDrawer(true)}/>{drawer&&<Drawer close={()=>setDrawer(false)}/>}<main className={styles.page} style={{maxWidth:"100%",overflow:"hidden"}}><header className={styles.pageHead}><div><h1>Warehouse</h1><p><b>Dashboard</b><span>/</span>Warehouse</p></div><FreightTabs/></header><div className={styles.mobileFreight}><FreightTabs/></div><div className={`${styles.desktopGrid} warehouse-mobile-grid`} style={{width:"100%",minWidth:0}}><Summary/><WarehouseInventory/><Capacity/><Storage/><Packages/><WarehouseMap floor={floor} setFloor={setFloor}/><Activity/></div><Footer/></main></>}
