"use client";

import { useMemo, useState } from "react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Icon } from "@/components/dashboard/icons";
import { AuthenticatedSidebarContent } from "@/components/dashboard/authenticated-sidebar-content";
import { activities, capacityUsage, inventoryByFreight, packageStatuses, storageRows, warehouseFloors, warehouseSummary, type FreightMode, type PackageStatus, type StorageRow } from "@/data/warehouse";
import { WarehouseInventory } from "./warehouse-inventory";
import styles from "./warehouse.module.css";
import "./warehouse-fixes.module.css";

const More=()=> <Icon name="more" className={styles.more}/>;
function MobileBar({open}:{open:()=>void}){return <header className={styles.mobileBar}><i/><strong>Warehouse</strong><button type="button" onClick={open} aria-label="Open navigation">☰</button></header>}
function Drawer({close}:{close:()=>void}){return <div className={styles.drawerBack} onClick={close}><aside onClick={event=>event.stopPropagation()}><AuthenticatedSidebarContent active="Warehouse" onNavigate={close} onClose={close}/></aside></div>}
function Footer(){return <footer className={styles.footer}><div><b>Copyright © 2025 Peterdraw</b><span>Privacy Policy</span><span>Term and conditions</span><span>Contact</span></div><div><span>ⓕ</span><span>𝕏</span><span>◎</span><span>▷</span><span>in</span></div></footer>}

function FreightTabs({value,onChange}:{value:FreightMode;onChange:(value:FreightMode)=>void}){const tabs:Array<{label:FreightMode;icon:React.ReactNode}>=[{label:"Road Freight",icon:<Icon name="truck" key="road"/>},{label:"Rail Freight",icon:<span key="rail">▥</span>},{label:"Ocean Freight",icon:<span key="ocean">◴</span>},{label:"Air Freight",icon:<span key="air">✈</span>}];return <div className={styles.freight} role="tablist" aria-label="Freight type">{tabs.map(tab=><button type="button" role="tab" aria-selected={value===tab.label} key={tab.label} className={value===tab.label?styles.freightActive:""} onClick={()=>onChange(tab.label)}>{tab.icon}{tab.label==="Road Freight"?tab.label:<b>{tab.label}</b>}</button>)}</div>}
function Summary(){return <div className={styles.summary} style={{width:"100%",minWidth:0}}>{warehouseSummary.map(item=><article key={item.label} style={{minWidth:0,overflow:"hidden"}}><small>{item.label}</small><div><strong>{item.value}</strong>{item.suffix&&<span>{item.suffix}</span>}<em>⌁ {item.change}</em></div></article>)}</div>}
function CapacityTooltip({active,payload}:{active?:boolean;payload?:Array<{name:string;value:number}>}){const segment=payload?.[0];if(!active||!segment)return null;const total=capacityUsage.reduce((sum,item)=>sum+item.value,0);return <div className={styles.capacityTooltip}><b>{segment.name}</b><span>{segment.value} shelves</span><small>{(segment.value/total*100).toFixed(1)}%</small></div>}
function Capacity(){const total=capacityUsage.reduce((sum,item)=>sum+item.value,0);const loaded=capacityUsage.find(item=>item.name==="Loaded")?.value??0;return <section className={styles.capacity}><header><h2>Capacity Usage</h2><More/></header><div className={styles.ring}><ResponsiveContainer width="100%" height="100%"><PieChart><Tooltip content={<CapacityTooltip/>} position={{x:132,y:0}} cursor={false} allowEscapeViewBox={{x:true,y:false}} wrapperStyle={{pointerEvents:"none",zIndex:4}}/><Pie data={capacityUsage} dataKey="value" nameKey="name" innerRadius="78%" outerRadius="100%" startAngle={90} endAngle={-270} stroke="none" isAnimationActive={false}>{capacityUsage.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie></PieChart></ResponsiveContainer><div><span>Total Usage</span><strong>{(loaded/total*100).toFixed(1)}%</strong></div></div><div className={styles.capacityLegend}>{capacityUsage.map(item=><p key={item.name}><span>{item.name}</span><b>{item.value} shelves</b></p>)}</div></section>}

type PackageFilter="All"|PackageStatus["status"];
function Packages(){const[filter,setFilter]=useState<PackageFilter>("All");const items=useMemo(()=>filter==="All"?packageStatuses:packageStatuses.filter(item=>item.status===filter),[filter]);return <section className={styles.packages}><header><h2>Package Status</h2><More/></header><div className={styles.statusTabs} role="tablist" aria-label="Package status">{(["All","Expected","Received","Sent"] as PackageFilter[]).map(tab=><button type="button" role="tab" aria-selected={filter===tab} className={filter===tab?styles.statusActive:""} key={tab} onClick={()=>setFilter(tab)}>{tab}</button>)}</div><div className={styles.packageList}>{items.length?items.map(item=><article key={item.id}><i><Icon name="box"/></i><p><b>{item.id}</b><span>{item.date}</span></p><em className={styles[item.status.toLowerCase()]}>{item.status}</em></article>):<p className={styles.empty}>No packages found.</p>}</div></section>}

type StorageSort=keyof StorageRow;
function Storage(){const[sortKey,setSortKey]=useState<StorageSort|null>(null);const[ascending,setAscending]=useState(true);const[floorFilter,setFloorFilter]=useState<number|null>(null);const rows=useMemo(()=>storageRows.filter(row=>floorFilter===null||row.floor===floorFilter).toSorted((a,b)=>{if(sortKey===null)return 0;const comparison=typeof a[sortKey]==="number"?(a[sortKey] as number)-(b[sortKey] as number):String(a[sortKey]).localeCompare(String(b[sortKey]),undefined,{numeric:true,sensitivity:"base"});return ascending?comparison:-comparison}),[sortKey,ascending,floorFilter]);const sort=(key:StorageSort)=>{if(key===sortKey)setAscending(value=>!value);else{setSortKey(key);setAscending(true)}};const headers:Array<[string,StorageSort]>=[["Floor","floor"],["Section","section"],["Category","category"],["Storage Used","used"],["Percentage","used"],["Available Space","available"]];return <section className={styles.storage}><header><h2>Warehouse Storage</h2><div><button type="button" onClick={()=>setFloorFilter(current=>current===null?1:current===3?null:current+1)}>▽ {floorFilter===null?"Filter":`Floor ${floorFilter}`}⌄</button><span>Sort by:</span><button type="button" onClick={()=>sort("section")}>Section{sortKey==="section"?(ascending?"↑":"↓"):"⌄"}</button><More/></div></header><div className={styles.storageScroll}><table><thead><tr>{headers.map(([label,key])=><th key={label} aria-sort={sortKey===key?(ascending?"ascending":"descending"):"none"}><button type="button" onClick={()=>sort(key)}>{label} {sortKey===key?(ascending?"↑":"↓"):"↕"}</button></th>)}</tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.section}><td>{row.floor}</td><td>{row.section}</td><td>{row.category}</td><td><div><i style={{width:`${row.used}%`}}/></div></td><td><b>{row.used}%</b></td><td><b>{row.available}</b><span>/100</span></td></tr>):<tr><td colSpan={6} className={styles.empty}>No storage rows found.</td></tr>}</tbody></table></div></section>}

function WarehouseMap({floor,setFloor}:{floor:number;setFloor:(floor:number)=>void}){const zones=warehouseFloors[floor];const selectFloor=(value:number)=>setFloor(Math.max(1,Math.min(3,value)));return <section className={styles.map} style={{overflow:"hidden"}}><header><h2>Warehouse Map</h2><div role="tablist" aria-label="Warehouse floor">{[1,2,3].map(value=><button type="button" role="tab" aria-selected={floor===value} key={value} className={floor===value?styles.floorActive:""} onClick={()=>setFloor(value)} onKeyDown={event=>{if(event.key==="ArrowRight"||event.key==="ArrowDown")selectFloor(floor===3?1:floor+1);if(event.key==="ArrowLeft"||event.key==="ArrowUp")selectFloor(floor===1?3:floor-1)}}>Floor {value}</button>)}</div></header><div className={styles.mapCanvas}><div className={`${styles.zones} warehouse-mobile-zone-grid`}>{zones.map(zone=><article key={zone.name} style={{minWidth:0,overflow:"hidden"}}><h3>{zone.name}</h3><div>{Array.from({length:zone.slots},(_,index)=>index+1).map(slot=><span className={zone.full.includes(slot)?styles.full:""} key={slot}>{zone.prefix}{slot}</span>)}</div><p>Available Space <b>{zone.available}/100</b></p></article>)}</div><p className={styles.mapLegend}><span/>Available <span/>Full</p></div></section>}
function Activity(){return <section className={styles.activity}><header><h2>Warehouse Activity Log</h2><More/></header><div>{activities.length?activities.map(item=><article key={item.id}><i className={item.purple?styles.purple:""}>{item.icon}</i><p><span><b>{item.name}</b> {item.text}</span><small>{item.time}</small></p></article>):<p className={styles.empty}>No activity records found.</p>}</div></section>}

export function WarehousePage(){const[floor,setFloor]=useState(1);const[freight,setFreight]=useState<FreightMode>("Road Freight");const[drawer,setDrawer]=useState(false);return <><MobileBar open={()=>setDrawer(true)}/>{drawer&&<Drawer close={()=>setDrawer(false)}/>}<main className={styles.page} style={{maxWidth:"100%",overflow:"hidden"}}><header className={styles.pageHead}><div><h1>Warehouse</h1><p><b>Dashboard</b><span>/</span>Warehouse</p></div><FreightTabs value={freight} onChange={setFreight}/></header><div className={styles.mobileFreight}><FreightTabs value={freight} onChange={setFreight}/></div><div className={`${styles.desktopGrid} warehouse-mobile-grid`} style={{width:"100%",minWidth:0}}><Summary/><WarehouseInventory items={inventoryByFreight[freight]} className={styles.tabletInventory}/><Capacity/><Storage/><Packages/><WarehouseMap floor={floor} setFloor={setFloor}/><Activity/></div><Footer/></main></>}
