import { Card, MoreButton } from "./ui";
import { Icon } from "./icons";

const rows=[["#SH9283746","TechGear Inc.","Electronics","FedEx","Los Angeles, CA → Chicago, IL","Mar 20, 2035","In Transit","bg-[#e7e7e7]"],["#SH9182635","StyleHub Co.","Apparel","DHL","New York, NY → Atlanta, GA","Mar 19, 2035","Out for Delivery","bg-[#ddd6fe] text-[#8065f4]"],["#SH9037821","FreshNest","Home & Kitchen","UPS","Dallas, TX → Miami, FL","Mar 18, 2035","Delivered","bg-[#def8e9] text-[#26a568]"],["#SH9374652","FitPlus Gear","Sports & Outdoors","USPS","Seattle, WA → Denver, CO","Mar 21, 2035","Processing","bg-[#dbeafe] text-[#3b82f6]"],["#SH9457830","AutoParts Pro","Automotive","Aramex","Detroit, MI → San Diego, CA","Mar 20, 2035","In Transit","bg-[#e7e7e7]"]];
export function RecentShipments(){return <Card title="Recent Shipments" action={<div className="flex items-center gap-2"><label className="flex h-8 w-[220px] items-center rounded-lg bg-[#f4f4f4] px-3"><Icon name="search" className="h-4 w-4"/><input aria-label="Search shipment" placeholder="Search shipment" className="ml-2 w-full bg-transparent text-[10px] outline-none"/></label><MoreButton/></div>} className="h-[403px]"><div className="mt-5 overflow-hidden"><table className="w-full table-fixed text-left text-[11px]"><thead className="h-11 bg-[#ddd6fe] text-[#56515f]"><tr><th className="w-8 rounded-l-lg px-2">□</th><th className="w-[14%]">Shipping ID ↕</th><th className="w-[16%]">Company ↕</th><th className="w-[12%]">Carriers ↕</th><th className="w-[27%]">Route ↕</th><th className="w-[16%]">Shipping Date ↕</th><th className="rounded-r-lg">Status ↕</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]} className="h-[58px] border-b border-[#eee] last:border-0"><td className="px-2 text-[#ddd]">□</td><td className="font-medium text-[#8065f4]">{r[0]}</td><td><b className="font-medium">{r[1]}</b><small className="block text-[9px] text-[#888]">{r[2]}</small></td><td>{r[3]}</td><td>{r[4]}</td><td>{r[5]}</td><td><span className={`rounded-full px-2 py-1 text-[9px] ${r[7]}`}>{r[6]}</span></td></tr>)}</tbody></table></div></Card>}

const activity=[["User @TechGuru99 submitted a bulk shipment request","12:00 PM"],["Customer Support @SupportKen added a priority tag to Order ID 77889JKL","11:30 AM"],["User @SallyMae88 initiated a return process for Order ID 44556GHI","11:00 AM"],["Administrator @AdminLisa resolved a delivery issue for Order ID 12345XYZ","10:15 AM"]];
export function RecentActivity(){return <Card title="Recent Activity" action={<MoreButton/>} className="h-[403px]"><ol className="relative mt-6 ml-3 border-l border-[#ddd] pl-8">{activity.map((a,i)=><li key={i} className="relative mb-7 last:mb-0"><span className={`absolute -left-[49px] top-0 grid h-9 w-9 place-items-center rounded-full ${i===2?"bg-[#ddd6fe]":"bg-[#eee]"}`}>{["□","◇","⟳","✓"][i]}</span><p className="text-[13px] leading-[18px]">{a[0].split("@").map((x,j)=>j===0?x:<span key={j} className="text-[#5d5fe7]">@{x}</span>)}</p><small className="mt-2 block text-[9px] text-[#999]">{a[1]}</small></li>)}</ol></Card>}

export function Footer(){return <footer className="flex h-[68px] items-center justify-between text-[11px] text-[#777]"><div className="flex gap-7"><b className="text-[#555]">Copyright © 2025 Peterdraw</b><span>Privacy Policy</span><span>Term and conditions</span><span>Contact</span></div><div className="flex gap-5 text-lg text-[#777]"><span>ⓕ</span><span>𝕏</span><span>◎</span><span>▻</span><span>in</span></div></footer>}
