"use client";

import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { activities, alerts, categories, chartData, freight, metrics, shipments } from "@/data/dashboard";
import { Icon, type DashboardIcon } from "./dashboard-icons";
import styles from "./dashboard.module.css";

function MoreButton(){return <button className={styles.iconButton} aria-label="More options"><Icon name="more"/></button>}
function Card({title, action, className="", children}:{title?:string;action?:React.ReactNode;className?:string;children:React.ReactNode}){return <section className={`${styles.card} ${className}`}><div className={styles.cardHead}>{title&&<h2>{title}</h2>}{action}</div>{children}</section>}
function Trend({children}:{children:React.ReactNode}){return <span className={styles.trend}><Icon name="trendUp" className={styles.trendIcon}/>{children}</span>}

function MetricCards(){return <div className={styles.metrics}>{metrics.map(metric=><Card key={metric.label} className={styles.metric}><span className={styles.muted}>{metric.label}</span><div className={styles.metricMain}><strong>{metric.value}</strong>{metric.suffix&&<small>{metric.suffix}</small>}<i><Icon name={metric.icon as DashboardIcon}/></i></div><p><Trend>{metric.change}</Trend> {metric.period}</p></Card>)}</div>}

const select=(label:string)=><button className={styles.select} type="button">{label}<Icon name="chevronDown" className={styles.selectChevron}/></button>;
type ShipmentBarShapeProps={x?:number;y?:number;width?:number;height?:number;index?:number;showCallout?:boolean};
function ShipmentBarShape({x=0,y=0,width=0,height=0,index=0,showCallout=true}:ShipmentBarShapeProps){const selected=index===4;return <g><path d={`M${x},${y+height}V${y}H${x+width}V${y+height}`} fill={selected?"url(#shipmentActive)":"url(#shipmentNormal)"} stroke={selected?"none":"#29292b"} strokeWidth={selected?0:1}/><line x1={x+width} y1={y} x2={x+width+7} y2={y} stroke="#29292b" strokeWidth="1.5"/>{selected&&<><line x1={x-7} y1={y} x2={x+width+7} y2={y} stroke="#29292b" strokeWidth="1.5"/><circle cx={x+width/2} cy={y} r="7" fill="#fff"/><circle cx={x+width/2} cy={y} r="5" fill="#29292b"/>{showCallout&&<foreignObject x={x+width/2-32} y={Math.max(0,y-57)} width="64" height="48"><div className={styles.shipmentAnnotation}><small>May 2030</small><b>3,124</b></div></foreignObject>}</>}</g>}
function ShipmentChart(){const [hoveredMonth,setHoveredMonth]=useState<string|null>(null);return <Card title="Shipment Statistic" action={select("Last Year")} className={styles.shipmentChart}><div className={`${styles.chartTotal} ${styles.shipmentTotal}`}>4,352 <Trend>+8.7%</Trend></div><div className={`${styles.chart} ${styles.shipmentPlot}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} barCategoryGap="5%" margin={{top:23,right:0,left:0,bottom:0}} onMouseMove={state=>setHoveredMonth(state.activeLabel ? String(state.activeLabel).trim() : null)} onMouseLeave={()=>setHoveredMonth(null)}><defs><linearGradient id="shipmentNormal" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#dedede"/><stop offset="1" stopColor="#fafafa"/></linearGradient><linearGradient id="shipmentActive" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8065f4"/><stop offset="1" stopColor="#f1edff"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#ececef" strokeWidth={1} strokeDasharray="3 3"/><XAxis dataKey="month" axisLine={false} tickLine={false} tickMargin={8} tick={{fontSize:9,fill:"#858589"}}/><YAxis width={42} domain={[0,4800]} ticks={[0,1200,2400,3600,4800]} axisLine={false} tickLine={false} tickMargin={6} tickFormatter={v=>v===0?"0K":`${v/1000}K`} tick={{fontSize:9,fill:"#858589"}}/><Tooltip content={<ShipmentHoverTooltip/>} cursor={false}/><Bar dataKey="shipments" shape={<ShipmentBarShape showCallout={hoveredMonth!=="May"}/>} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></Card>}
function ShipmentHoverTooltip({active,payload}:{active?:boolean;payload?:Array<{value:number;payload:{month:string;year:number}}>}){const point=payload?.[0]?.payload;if(!active||!point)return null;return <div className={`${styles.tooltip} ${styles.shipmentHoverTooltip}`}><small>{point.month} {point.year}</small><b>{payload[0].value.toLocaleString()}</b></div>}
function ProfitChart(){return <Card title="Profit Summary" action={select("Last 8 Months")} className={styles.profitChart}><div className={styles.profitTop}><div className={`${styles.chartTotal} ${styles.profitMetric}`}>$624,550 <Trend>5.62%</Trend></div><div className={`${styles.legend} ${styles.profitLegend}`}><span><i/>Revenue</span><span><i/>Cost</span></div></div><div className={`${styles.chart} ${styles.profitPlot}`}><div className={styles.profitStaticTooltip} role="status"><div><i/><span>Revenue</span><b>$87,524</b></div><div><i/><span>Cost</span><b>$45,680</b></div></div><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} barGap={3} barCategoryGap="17%" margin={{top:18,right:0,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#ececef" strokeWidth={1}/><XAxis dataKey="month" axisLine={false} tickLine={false} tickMargin={8} tick={{fontSize:9,fill:"#858589"}}/><YAxis width={44} domain={[0,100000]} ticks={[0,25000,50000,75000,100000]} axisLine={false} tickLine={false} tickMargin={6} tickFormatter={v=>v===0?"$0":`$${v/1000}K`} tick={{fontSize:9,fill:"#858589"}}/><Tooltip content={<ProfitTooltip/>} cursor={false}/><Bar dataKey="revenue" fill="#ddd6fb" radius={[4,4,0,0]} barSize={18} isAnimationActive={false}>{chartData.map((_,i)=><Cell key={i} fill={i===4?"#8065f4":"#ddd6fb"}/>)}</Bar><Bar dataKey="cost" fill="#ededee" radius={[4,4,0,0]} barSize={18} isAnimationActive={false}>{chartData.map((_,i)=><Cell key={i} fill={i===4?"#29292b":"#ededee"}/>)}</Bar></BarChart></ResponsiveContainer></div></Card>}
function ProfitTooltip({active,payload}:{active?:boolean;payload?:Array<{name:string;value:number;color:string}>}){if(!active||!payload?.length)return null;return <div className={styles.profitTooltip}>{payload.map(x=><div key={x.name}><i style={{background:x.color}}/><span>{x.name}</span><b>${x.value.toLocaleString()}</b></div>)}</div>}

function ShipmentType(){return <Card title="Shipment Type" action={<MoreButton/>} className={styles.shipmentType}><div className={styles.donut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={freight} dataKey="value" innerRadius="70%" outerRadius="92%" startAngle={90} endAngle={-270} stroke="none">{freight.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie></PieChart></ResponsiveContainer><div><small>Total Shipment</small><strong>2,500</strong></div></div><div className={styles.freightLegend}>{freight.map(x=><div key={x.name}><b style={{background:x.color,color:x.value===9?"#444":"white"}}>{x.value}%</b><p>{x.name}<small>{x.count}</small></p></div>)}</div></Card>}
function ProductCategories(){return <Card title="Product Categories" action={<MoreButton/>} className={styles.categories}><div className={styles.categoryTotal}><span>Total Products</span><strong>1,000</strong></div><div className={styles.categoryBar}>{categories.map(x=><i key={x.name} style={{width:`${x.percent}%`,background:x.color}}/>)}</div><ul>{categories.map(x=><li key={x.name}><i style={{background:x.color}}/><span>{x.name}</span><em>{x.products} products</em><b>{x.percent}%</b></li>)}</ul></Card>}

function TrackingPanel(){return <Card className={styles.tracking}><div className={styles.trackingContent}><label className={styles.mapSearch}><input aria-label="Search by Shipping ID" placeholder="Search by Shipping ID..."/><Icon name="search"/></label><div className={styles.mapControls}><button aria-label="Zoom in"><Icon name="plus" className={styles.mapControlIcon}/></button><button aria-label="Zoom out"><Icon name="minus" className={styles.mapControlIcon}/></button></div><svg className={styles.routeMap} viewBox="0 0 455 230" preserveAspectRatio="none" aria-hidden="true"><path d="M-5 126 L235 80" fill="none" stroke="#29292b" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/><path d="M235 80 L465 33" fill="none" stroke="#8065f4" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/><circle cx="235" cy="80" r="16.5" fill="#ddd6fe" opacity=".32"/><circle cx="235" cy="80" r="12.5" fill="#8065f4"/><g transform="translate(235 80) rotate(72) scale(.65) translate(-10 -10)"><path d="M10 1 18.2 15.5 12.25 12.85 10 19 7.75 12.85 1.8 15.5Z" fill="#fff"/><path d="m10 11.2 1.15 4.15L10 17.1l-1.15-1.75Z" fill="#8065f4"/></g></svg><div className={styles.trackingInfo}><div className={styles.trackingTop}><div><strong>#SH8743921</strong><p><span>In Transit</span> On Schedule</p></div><p>Courier:<b>Daniel Cooper</b>SkyLogix Express</p></div><div className={styles.progress}><i/><i><Icon name="truck"/></i><i/></div><div className={styles.locations}><p>San Francisco, CA, USA<small>Mar 19, 2035 - 10:30 AM</small></p><p>New York, NY, USA<small>Mar 23, 2035 - 03:00 PM (estimated)</small></p></div></div></div></Card>}

function AlertsPanel(){return <Card title="Shipment Alerts" action={<MoreButton/>} className={styles.alerts}><div className={styles.alertTotal}><strong>12</strong> Delays Detected</div><div className={styles.alertSummary}>{[[5,"Customs Clearance Delay"],[4,"Incorrect Address Provided"],[3,"Weather-Related Hold"]].map(x=><div key={x[1] as string}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><ul>{alerts.map(a=><li key={a.id}><i><Icon name={a.icon}/></i><p>{a.title}<small><b>{a.id}</b> · {a.type} · {a.date}</small></p><Icon name="arrow"/></li>)}</ul></Card>}

function RecentShipments(){const [query,setQuery]=useState("");const [selected,setSelected]=useState<string[]>([]);const [asc,setAsc]=useState(true);const rows=useMemo(()=>shipments.filter(x=>`${x.id} ${x.company}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(asc?1:-1)*(shipments.indexOf(a)-shipments.indexOf(b))),[query,asc]);const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);return <Card title="Recent Shipments" className={styles.recentShipments} action={<div className={styles.tableActions}><label><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search shipment" placeholder="Search shipment"/></label><button aria-label="Sort shipments" onClick={()=>setAsc(x=>!x)}><Icon name="sort"/></button><MoreButton/></div>}><div className={styles.tableWrap}><table><colgroup><col className={styles.recentCheckboxColumn}/><col className={styles.recentIdColumn}/><col className={styles.recentCompanyColumn}/><col className={styles.recentCarrierColumn}/><col className={styles.recentRouteColumn}/><col className={styles.recentDateColumn}/><col className={styles.recentStatusColumn}/></colgroup><thead><tr><th><input type="checkbox" aria-label="Select all shipments" checked={selected.length===rows.length&&rows.length>0} onChange={()=>setSelected(selected.length===rows.length?[]:rows.map(x=>x.id))}/></th>{["Shipping ID","Company","Carriers","Route","Shipping Date","Status"].map(x=><th key={x}>{x}<Icon name="columnSort" className={styles.columnSortIcon}/></th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><input type="checkbox" aria-label={`Select ${x.id}`} checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/></td><td><a href="#">{x.id}</a></td><td><b>{x.company}</b><small>{x.category}</small></td><td>{x.carrier}</td><td>{x.route}</td><td>{x.date}</td><td><span className={x.status==="Out for Delivery"?styles.outForDelivery:undefined} data-status={x.status}>{x.status}</span></td></tr>)}</tbody></table></div></Card>}

function ActivityTimeline(){return <Card title="Recent Activity" action={<MoreButton/>} className={styles.activity}><ol>{activities.map((a,i)=><li key={a.time}><i><Icon name={a.icon}/></i><p>{a.text} <a href="#">{a.user}</a>{a.rest}<small>{a.time}</small></p>{i<activities.length-1&&<span/>}</li>)}</ol></Card>}
function Footer(){return <footer className={styles.footer}><div><b>Copyright © 2025 Peterdraw</b><a href="#">Privacy Policy</a><a href="#">Term and conditions</a><a href="#">Contact</a></div><nav aria-label="Social media"><a href="#" aria-label="Facebook">f</a><a href="#" aria-label="X">𝕏</a><a href="#" aria-label="Instagram">◎</a><a href="#" aria-label="YouTube">▷</a><a href="#" aria-label="LinkedIn">in</a></nav></footer>}

export function DashboardPage(){return <main className={styles.page}><div className={styles.dashboardGrid}><MetricCards/><ShipmentChart/><ProfitChart/><ShipmentType/><div className={styles.dashboardMiddleRow}><ProductCategories/><TrackingPanel/><AlertsPanel/></div><div className={styles.dashboardBottomRow}><RecentShipments/><ActivityTimeline/></div></div><Footer/></main>}
