import { Card, KpiCard, MoreButton, SelectButton } from "./ui";
import { DonutChart, ProfitBars, ShipmentBars } from "./charts";
import { Icon } from "./icons";

export function Kpis() { return <div className="grid grid-cols-3 gap-5"><KpiCard label="Active Shipments" value="1,284" suffix="shipments" change="+8.7%" period="from last week" icon="truck"/><KpiCard label="Delivery Performance" value="94.3%" suffix="on-time" change="-1.2%" period="from last week" icon="chart"/><KpiCard label="Revenue" value="$82,450" change="+12.4%" period="from last month" icon="money"/></div>; }

export function ChartsRow() { return <div className="grid h-[259px] grid-cols-[0.9fr_1.15fr] gap-5"><Card title="Shipment Statistic" action={<SelectButton>Last Year </SelectButton>}><p className="mt-4 text-[24px] font-bold">4,352 <span className="rounded-full bg-[#def8e9] px-2 py-1 align-middle text-[10px] text-[#36ac70]">↗ +8.7%</span></p><ShipmentBars/></Card><Card title="Profit Summary" action={<SelectButton>Last 8 Months </SelectButton>}><div className="mt-4 flex items-center justify-between"><p className="text-[24px] font-bold">$624,550 <span className="rounded-full bg-[#def8e9] px-2 py-1 align-middle text-[10px] text-[#36ac70]">↗ 5.62%</span></p><p className="text-[10px] text-[#888]"><i className="mr-1 inline-block h-2 w-2 bg-[#8065f4]"/>Revenue <i className="ml-3 mr-1 inline-block h-2 w-2 bg-[#292929]"/>Cost</p></div><ProfitBars/></Card></div>; }

const freight=[["46%","Road Freight","1,150 shipment","bg-[#8065f4]"],["17%","Ocean Freight","425 shipments","bg-[#777]"],["28%","Air Freight","700 shipments","bg-[#292929]"],["9%","Rail Freight","225 shipments","bg-[#aaa]"]];
export function ShipmentType() { return <Card title="Shipment Type" action={<MoreButton/>} className="h-[394px]"><DonutChart/><div className="mt-5 grid grid-cols-2 gap-x-4 gap-y-3">{freight.map(x=><div key={x[1]} className="flex items-start"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-md text-[10px] font-semibold text-white ${x[3]}`}>{x[0]}</span><p className="ml-2 text-[11px] font-medium">{x[1]}<small className="mt-1 block text-[9px] font-normal text-[#888]">{x[2]}</small></p></div>)}</div></Card>; }

const categories=[["Electronics","240 products","24%","bg-[#8065f4]"],["Home & Kitchen","200 products","20%","bg-[#dcd5fb]"],["Apparel","180 products","18%","bg-[#292929]"],["Beauty & Health","140 products","14%","bg-[#777]"],["Sports & Outdoors","120 products","12%","bg-[#ccc]"],["Automotive","120 products","12%","bg-[#eee]"]];
export function ProductCategories() { return <Card title="Product Categories" action={<MoreButton/>} className="h-[441px]"><div className="mt-5 flex items-center justify-between"><span className="text-[13px] text-[#888]">Total Products</span><b className="text-[25px]">1,000</b></div><div className="mt-5 flex h-[54px] gap-1 overflow-hidden rounded-lg">{categories.map((c,i)=><i key={c[0]} className={c[3]} style={{width:[24,20,18,14,12,12][i]+"%"}}/>)}</div><ul className="mt-7 space-y-[17px]">{categories.map(c=><li key={c[0]} className="flex items-center text-[13px]"><i className={`mr-3 h-2.5 w-2.5 rounded-full ${c[3]}`}/><span>{c[0]}</span><span className="ml-auto rounded bg-[#f4f4f4] px-2 py-1 text-[11px] text-[#888]">{c[1]}</span><b className="ml-2 text-[11px]">{c[2]}</b></li>)}</ul></Card>; }

export function TrackingMap() { return <Card className="relative h-[441px] overflow-hidden bg-[#ededed] p-3"><label className="absolute left-5 top-5 z-10 flex h-10 w-[255px] items-center rounded-xl bg-white px-4 shadow-lg"><input aria-label="Search by Shipping ID" placeholder="Search by Shipping ID..." className="w-full bg-transparent text-[11px] outline-none"/><Icon name="search" className="h-4 w-4"/></label><div className="absolute inset-x-0 top-[145px] rotate-[-11deg] border-t-4 border-[#292929]"/><div className="absolute left-[48%] top-[122px] z-10 grid h-8 w-8 place-items-center rounded-full bg-[#8065f4] text-white shadow-lg">➤</div><div className="absolute left-[48%] right-0 top-[133px] rotate-[-11deg] border-t-4 border-[#8065f4]"/><div className="absolute bottom-3 left-3 right-3 rounded-xl bg-white p-4 shadow-lg"><div className="flex justify-between"><div><b className="text-[14px]">#SH8743921</b><p className="mt-1 text-[10px]"><span className="rounded bg-[#ddd6fe] px-2 py-1">In Transit</span> <span className="text-[#888]">On Schedule</span></p></div><p className="text-[10px] text-[#888]">Courier:<b className="block text-[#333]">Daniel Cooper</b>SkyLogix Express</p></div><div className="relative my-5 border-t-4 border-[#8065f4]"><i className="absolute -left-1 -top-2 h-4 w-4 rounded-full border-2 border-[#8065f4] bg-white"/><i className="absolute left-[65%] -top-3 grid h-6 w-6 place-items-center rounded-full bg-[#8065f4] text-white">⌁</i><i className="absolute -right-1 -top-2 h-4 w-4 rounded-full border-2 border-[#ddd] bg-white"/></div><div className="flex justify-between"><p className="text-[13px] font-semibold">San Francisco, CA, USA<small className="block text-[9px] font-normal text-[#888]">Mar 19, 2035 - 10:30 AM</small></p><p className="text-right text-[13px] font-semibold">New York, NY, USA<small className="block text-[9px] font-normal text-[#888]">Mar 23, 2035 - 03:00 PM (estimated)</small></p></div></div></Card>; }

const alerts=[["Customs Clearance Delay","#SH8743921 · Ocean Freight · Mar 20"],["Incorrect Address Provided","#SH8725810 · Road Freight · Mar 20"],["Weather-Related Hold","#SH8790043 · Air Freight · Mar 19"],["Incorrect Address Provided","#SH8716654 · Rail Freight · Mar 18"]];
export function ShipmentAlerts() { return <Card title="Shipment Alerts" action={<MoreButton/>} className="h-[441px]"><p className="mt-5 text-[25px] font-bold">12 <span className="text-[13px] font-normal text-[#888]">Delays Detected</span></p><div className="mt-5 grid grid-cols-3 gap-2">{[[5,"Customs Clearance Delay"],[4,"Incorrect Address Provided"],[3,"Weather-Related Hold"]].map(x=><div key={x[1]} className="rounded-lg bg-[#ddd6fe] p-3 text-center"><b className="text-xl">{x[0]}</b><p className="mt-3 text-[10px] leading-3">{x[1]}</p></div>)}</div><ul className="mt-6 space-y-4">{alerts.map((a,i)=><li key={i} className="flex items-center"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f3f3f3] text-xs">◇</span><p className="ml-3 text-[11px] font-medium">{a[0]}<small className="mt-1 block text-[9px] font-normal text-[#888]"><b className="text-[#8065f4]">{a[1].split(" · ")[0]}</b> · {a[1].split(" · ").slice(1).join(" · ")}</small></p><span className="ml-auto">↗</span></li>)}</ul></Card>; }
